baseURL = ""
title = "Educenter | hugo education template"
theme = "educenter hugo"
paginate = "6"
summaryLength = "10"
disqusShortname = "educenter"
disableLanguages = [ ]
themesDir = "themes"
publishDir = "public"

[params]
logo = "images/logo.png"
description = "This is meta description"
author = "Themefisher"
address = "9567 Turner Trace Apt. BC C3G8A4"
mobile = "+211234565523"
email = "info@educenter.com"
contact_form_action = "#"
google_analitycs_id = ""
top_header = true

[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"

[[params.plugins.css]]
link = "plugins/slick/slick.css"

[[params.plugins.css]]
link = "plugins/animate/animate.css"

[[params.plugins.css]]
link = "plugins/venobox/venobox.css"

[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"

[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"

[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

  [params.preloader]
  enable = true
  preloader = "images/preloader.gif"

  [params.subscription]
  enable = true
  mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074"
  mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074"

  [params.map]
  enable = true
  gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
  map_latitude = "51.5223477"
  map_longitude = "-0.1622023"
  map_marker = "images/marker.png"

  [params.cookies]
  enable = true
  expire_days = 2

  [[params.social]]
  title = "facebook"
  icon = "ti-facebook"
  link = "#"

  [[params.social]]
  title = "twitter"
  icon = "ti-twitter-alt"
  link = "#"

  [[params.social]]
  title = "instagram"
  icon = "ti-instagram"
  link = "#"

  [[params.social]]
  title = "github"
  icon = "ti-github"
  link = "#"

  [[params.social]]
  title = "linkedin"
  icon = "ti-linkedin"
  link = "#"

[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"

[[Languages.en.menu.main]]
name = "About"
url = "about"
weight = 1

[[Languages.en.menu.main]]
name = "course"
url = "course"
weight = 2

[[Languages.en.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

[[Languages.en.menu.main]]
parent = "Pages"
name = "teacher"
url = "teacher"

[[Languages.en.menu.main]]
parent = "Pages"
name = "notice"
url = "notice"

[[Languages.en.menu.main]]
parent = "Pages"
name = "event"
url = "event"

[[Languages.en.menu.main]]
parent = "Pages"
name = "scholarship"
url = "scholarship"

[[Languages.en.menu.main]]
parent = "Pages"
name = "research"
url = "research"

[[Languages.en.menu.main]]
name = "blog"
url = "blog"
weight = 4

[[Languages.en.menu.main]]
name = "Contact"
url = "contact"
weight = 5

[[Languages.en.menu.footer]]
name = "teacher"
url = "teacher"

[[Languages.en.menu.footer]]
name = "notice"
url = "notice"

[[Languages.en.menu.footer]]
name = "event"
url = "event"

[[Languages.en.menu.footer]]
name = "scholarship"
url = "scholarship"

[[Languages.en.menu.footer]]
name = "research"
url = "research"

[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"

[[Languages.fr.menu.main]]
name = "À propos"
url = "about"
weight = 1

[[Languages.fr.menu.main]]
name = "Cours"
url = "course"
weight = 2

[[Languages.fr.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

[[Languages.fr.menu.main]]
parent = "Pages"
name = "teacher"
url = "teacher"

[[Languages.fr.menu.main]]
parent = "Pages"
name = "notice"
url = "notice"

[[Languages.fr.menu.main]]
parent = "Pages"
name = "Évènement"
url = "event"

[[Languages.fr.menu.main]]
parent = "Pages"
name = "Cursus"
url = "scholarship"

[[Languages.fr.menu.main]]
parent = "Pages"
name = "research"
url = "research"

[[Languages.fr.menu.main]]
name = "blog"
url = "blog"
weight = 4

[[Languages.fr.menu.main]]
name = "Contact"
url = "contact"
weight = 5

[[Languages.fr.menu.footer]]
name = "teacher"
url = "teacher"

[[Languages.fr.menu.footer]]
name = "notice"
url = "notice"

[[Languages.fr.menu.footer]]
name = "event"
url = "event"

[[Languages.fr.menu.footer]]
name = "scholarship"
url = "scholarship"

[[Languages.fr.menu.footer]]
name = "research"
url = "research"
